export const theme = {
  colors: {
    background: '#F8FAFC',
    surface: '#FFFFFF',
    primary: '#7C3AED',
    primaryDark: '#4C1D95',
    primaryLight: '#A78BFA',
    primaryGradient: ['#7C3AED', '#8B5CF6'],
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textTertiary: '#64748B',
    border: '#E2E8F0',
    cardSurface: '#FFFFFF',
    focusRing: '#7C3AED',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
    mastery: {
      BE: '#EF4444',
      AE: '#F59E0B',
      ME: '#22C55E',
      EE: '#3B82F6',
    },
    gradients: {
      primary: ['#7C3AED', '#8B5CF6'],
      success: ['#10B981', '#34D399'],
      warning: ['#F59E0B', '#FBBF24'],
      error: ['#EF4444', '#F87171'],
      info: ['#3B82F6', '#60A5FA'],
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    card: 16,
    pill: 999,
    xl: 24,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 40,
    },
    h2: {
      fontSize: 24,
      fontWeight: '600' as const,
      lineHeight: 32,
    },
    h3: {
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 28,
    },
    body: {
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    bodyMedium: {
      fontSize: 16,
      fontWeight: '500' as const,
      lineHeight: 24,
    },
    caption: {
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    captionMedium: {
      fontSize: 14,
      fontWeight: '500' as const,
      lineHeight: 20,
    },
    small: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  layout: {
    headerHeight: 60,
    tabBarHeight: 80,
    cardPadding: 20,
    screenPadding: 16,
  },
} as const;

export type Theme = typeof theme;
